spring.application.name=applyflow
spring.datasource.url=jdbc:postgresql://localhost:5432/applyflow_db
spring.datasource.username=postgres
spring.datasource.password=Matin.py@180183

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=YzJlYjEwYTgwZjc5MGE2MWJmMDYxYjc4MTNhYjljMjYxMmI5ODdmMDZjOWQ4OWIxN2Y1MDFjZjNlMTIwMTgzOQ==
jwt.expiration=86400000